// Code generated by tyrellcorp. DO NOT EDIT.
// source: record.proto.tpl

syntax = "proto3";
package {{ .Package | ToLower | Trim }};

import "google/protobuf/timestamp.proto";

option go_package = "{{ .Repository | ToLower | Trim }}/{{ .Package | ToLower | Trim }}";
option java_multiple_files = true;
option java_outer_classname = "RecordProto";
option java_package = "com.tyrellcorp.{{ .Package | ToLower | Trim }}";

message RecordInfo {
	google.protobuf.Timestamp created = 1;
	string created_by = 2;

	google.protobuf.Timestamp updated = 3;
	string updated_by = 4;

	enum Status {
		draft = 0;
		active = 1;
		archived = 2;
		invalid = 3;
	}

	Status status = 5;
}
