// Code generated by tyrellcorp. DO NOT EDIT.
// source: composition.go.tpl

package config

type ServerCfg struct {
	RpcPort   string
	HttpPort  string
	HttpsPort string
	TlsCert   string
	TlsKey    string
}

type DbCfg struct {
	Addr     string
	Port     string
	DbName   string
	User     string
	Password string
}

type Composition struct {
	Server *ServerCfg
	Db     *DbCfg
}
